import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "on-tertiary-fixed-variant": "#4a00a4",
        "secondary": "#d8e3fb",
        "on-tertiary": "#2b0065",
        "tertiary-fixed-dim": "#b48fff",
        "surface-container-low": "#091328",
        "surface-container": "#0f1930",
        "surface-variant": "#192540",
        "on-primary-fixed-variant": "#006b4f",
        "on-secondary-container": "#c5d1e8",
        "outline-variant": "#40485d",
        "surface-container-highest": "#192540",
        "error-dim": "#d7383b",
        "secondary-dim": "#cad5ed",
        "secondary-container": "#3c475a",
        "primary-fixed-dim": "#58f0bd",
        "on-error-container": "#ffa8a3",
        "on-primary-container": "#003828",
        "on-error": "#490006",
        "on-secondary": "#475266",
        "surface-bright": "#1f2b49",
        "inverse-on-surface": "#4d556b",
        "surface-container-high": "#141f38",
        "secondary-fixed": "#d8e3fb",
        "primary-container": "#18c897",
        "tertiary-fixed": "#c0a0ff",
        "primary-fixed": "#68ffca",
        "on-tertiary-container": "#ffffff",
        "inverse-primary": "#006c50",
        "tertiary": "#af88ff",
        "primary": "#68ffca",
        "on-tertiary-fixed": "#200051",
        "surface-tint": "#68ffca",
        "tertiary-container": "#8342f4",
        "error": "#ff716c",
        "error-container": "#9f0519",
        "on-secondary-fixed-variant": "#515c70",
        "on-secondary-fixed": "#354053",
        "inverse-surface": "#faf8ff",
        "on-primary-fixed": "#004b36",
        "secondary-fixed-dim": "#cad5ed",
        "primary-dim": "#58f0bd",
        "surface-container-lowest": "#000000",
        "surface-dim": "#060e20",
        "on-surface": "#dee5ff",
        "on-surface-variant": "#a3aac4",
        "outline": "#6d758c",
        "on-primary": "#005f46",
        "surface": "#060e20",
        "tertiary-dim": "#8a4cfc",
        "on-background": "#dee5ff"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
export default config;
